/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smart_lock_utils_DaemUtil */

#ifndef _Included_com_smart_lock_utils_DaemUtil
#define _Included_com_smart_lock_utils_DaemUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smart_lock_utils_DaemUtil
 * Method:    createWatcher
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_smart_lock_utils_DaemUtil_createWatcher
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_smart_lock_utils_DaemUtil
 * Method:    connectToMonitor
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_smart_lock_utils_DaemUtil_connectToMonitor
  (JNIEnv *, jobject);

/*
 * Class:     com_smart_lock_utils_DaemUtil
 * Method:    sendMsgToMonitor
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_smart_lock_utils_DaemUtil_sendMsgToMonitor
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
